In [1]:
#Importing Dependencies
import pandas as pd
from datetime import date
import random

In [2]:
#Reading in CSV file
raw_csv= "../US_econ_stats.csv"

econ_df = pd.read_csv(raw_csv)

In [3]:
econ_df

,Unnamed: 0,2013,2014,2015,2016,2017,2018,2019,2020
0,GDP_per_capita (USD current PPPs),53241.10,55081.54,56731.07,57846.27,59896.76,62783.98,65055.79,63285.23
1,Gross_national_income_(GNI)_per_capita (USD cu...,54332.07,56626.93,58148.53,58853.04,61168.05,64067.42,66078.74,64475.26
2,Household_disposable_income (Annual growth %),-1.15,3.74,3.90,NaN,NaN,NaN,NaN,NaN
3,Real_GDP_growth (Annual growth %),1.84,2.29,2.71,1.67,2.26,2.92,2.29,-3.40
4,Net_saving_rate_in_household_disposable_income...,6.32,7.28,7.78,7.22,7.52,7.88,7.90,17.05
...,...,...,...,...,...,...,...,...,...
95,Suicide_Rates (Per 100 000 persons),13.10,13.50,13.80,14.00,14.50,NaN,NaN,NaN
96,Goods_transport (Mln tonne-km),6644027.40,6813036.40,6686902.20,6549374.80,6659498.00,NaN,NaN,NaN
97,Passenger_transport (Mln passenger-km),6198646.10,6218169.11,6429085.69,6547948.16,6591556.54,NaN,NaN,NaN
98,Road_Fatalities (Per mln inhabitants),103.52,102.63,110.64,115.95,115.26,111.86,109.94,117.40
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
mapping = {econ_df.columns[0]: 'Stats'}
econ_df = econ_df.rename(columns=mapping)
econ_df

,Stats,2013,2014,2015,2016,2017,2018,2019,2020
0,GDP_per_capita (USD current PPPs),53241.10,55081.54,56731.07,57846.27,59896.76,62783.98,65055.79,63285.23
1,Gross_national_income_(GNI)_per_capita (USD cu...,54332.07,56626.93,58148.53,58853.04,61168.05,64067.42,66078.74,64475.26
2,Household_disposable_income (Annual growth %),-1.15,3.74,3.90,NaN,NaN,NaN,NaN,NaN
3,Real_GDP_growth (Annual growth %),1.84,2.29,2.71,1.67,2.26,2.92,2.29,-3.40
4,Net_saving_rate_in_household_disposable_income...,6.32,7.28,7.78,7.22,7.52,7.88,7.90,17.05
...,...,...,...,...,...,...,...,...,...
95,Suicide_Rates (Per 100 000 persons),13.10,13.50,13.80,14.00,14.50,NaN,NaN,NaN
96,Goods_transport (Mln tonne-km),6644027.40,6813036.40,6686902.20,6549374.80,6659498.00,NaN,NaN,NaN
97,Passenger_transport (Mln passenger-km),6198646.10,6218169.11,6429085.69,6547948.16,6591556.54,NaN,NaN,NaN
98,Road_Fatalities (Per mln inhabitants),103.52,102.63,110.64,115.95,115.26,111.86,109.94,117.40
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
econ_df.dtypes

Stats     object
2013     float64
2014     float64
2015     float64
2016     float64
2017     float64
2018     float64
2019     float64
2020     float64
dtype: object

In [6]:
econ_df['Stats'] = econ_df['Stats'].astype('string')
econ_df.dtypes

Stats     string
2013     float64
2014     float64
2015     float64
2016     float64
2017     float64
2018     float64
2019     float64
2020     float64
dtype: object

In [7]:
econ_df = econ_df.dropna()

In [8]:
econ_df['Stats'].tolist()

['GDP_per_capita (USD current PPPs)',
 'Gross_national_income_(GNI)_per_capita (USD current PPPs) (USD current PPPs)',
 'Real_GDP_growth (Annual growth %)',
 'Net_saving_rate_in_household_disposable_income (%)',
 'Gross_fixed_capital_formation (Annual growth %)',
 'Government_deficit (% of GDP)',
 'General_government_debt (% of GDP)',
 'General_government_revenues (% of GDP)',
 'General_government_expenditures (% of GDP)',
 'Private_pension_expenditure (% of GDP)',
 'Total_tax_revenue (% of GDP)',
 'Tax_on_personal_income (% of GDP)',
 'Tax_on_corporate_profits (% of GDP)',
 'Taxes_on_goods_and_services (% of GDP)',
 'Taxes_on_the_average_worker (% of labour cost)',
 'Imports_of_goods_and_services (% of GDP)',
 'Exports_of_goods_and_services (% of GDP)',
 'Goods_trade_balance:_exports_minus_imports_of_goods (Bln USD)',
 'Imports_of_goods (Bln USD)',
 'Exports_of_goods (Bln USD)',
 'Service_trade_balance:_exports_minus_imports_of_services (Bln USD)',
 'Imports_of_services (Bln USD)',
 'Exports_of_services (Bln USD)',
 'Current_account_balance_of_payments (% of GDP)',
 'Outward_FDI_stocks (Mln USD)',
 'Inward_FDI_stocks (Mln USD)',
 'Inflows_of_foreign_direct_investment (Mln USD)',
 'Outflows_of_foreign_direct_investment (Mln USD)',
 'Inflation_rate:_all_items (Annual growth %)',
 'Inflation_rate:_all_items_non_food_non_energy (Annual growth %)',
 'Inflation_rate:_food (Annual growth %)',
 'Inflation_rate:_energy (Annual growth %)',
 'Producer_Price_Indices_(PPI):_manufacturing (Annual growth %)',
 'Long-term_interest_rates (%)',
 'Purchasing_power_parities (USD per USD)',
 'Exchange_rates (USD per USD)',
 'Indices_of_price_levels (OECD=100)',
 'Total_primary_energy_supply_(TPES) (Mtoe)',
 "TPES_per_unit_of_GDP_at_2000_prices_and_PPPs (Toe per '000 USD)",
 'Crude_oil_import_prices (USD per barrel)',
 'CO2_emissions_from_fuel_combustion (Mln tonnes)',
 'Tertiary_attainment_in_population_aged_25-64 (%)',
 'Youths_15-19_not_in_education_nor_employment (%)',
 'Youths_20-24_not_in_education_nor_employment (%)',
 'Employment_rate_in_population_aged_15-24 (%)',
 'Employment_rate_in_population_aged_25-54 (%)',
 'Employment_rate_in_population_aged_55-64 (%)',
 'Self-employment_rate:_total_employment (%)',
 'Self-employment_rate:_male_employment (%)',
 'Self-employment_rate:_female_employment (%)',
 'Unemployment_rate:_total_labour_force (%)',
 'Unemployment_rate:_male_labour_force (%)',
 'Unemployment_rate:_female_labour_force (%)',
 'Long-term_unemployment:_total_unemployed (%)',
 'Labour_compensation_per_unit_labour_input,_total_economy (Annual growth %)',
 'Average_time_worked_per_person_in_employment (Hours per year)',
 "Total_population ('000 persons)",
 'Population_growth_rates (%)',
 'Youth_population_aged_less_than_15 (% of population)',
 'Elderly_population_aged_65_and_over (% of population)',
 'Life_expectancy_at_birth (Years)',
 'Life_expectancy_at_birth:_men (Years)',
 'Life_expectancy_at_birth:_women (Years)',
 'Road_Fatalities (Per mln inhabitants)']

In [9]:
stats_wanted = ["Real_GDP_growth (Annual growth %)", "Net_saving_rate_in_household_disposable_income (%)", 
                "Tax_on_corporate_profits (% of GDP)", "Taxes_on_goods_and_services (% of GDP)", 
                "Imports_of_goods_and_services (% of GDP)", "Exports_of_goods_and_services (% of GDP)", 
                "Inflation_rate:_all_items (Annual growth %)", "Long-term_interest_rates (%)", 
                "Unemployment_rate:_total_labour_force (%)", "Tertiary_attainment_in_population_aged_25-64 (%)",
                "Life_expectancy_at_birth (Years)", "Population_growth_rates (%)", 
                "Purchasing_power_parities (USD per USD)", 
                "Labour_compensation_per_unit_labour_input,_total_economy (Annual growth %)"]

new_econ_df = econ_df[econ_df.Stats.isin(stats_wanted)]
new_econ_df

,Stats,2013,2014,2015,2016,2017,2018,2019,2020
3,Real_GDP_growth (Annual growth %),1.84,2.29,2.71,1.67,2.26,2.92,2.29,-3.40
4,Net_saving_rate_in_household_disposable_income...,6.32,7.28,7.78,7.22,7.52,7.88,7.90,17.05
20,Tax_on_corporate_profits (% of GDP),2.09,2.26,2.12,1.95,1.54,1.32,1.34,1.32
21,Taxes_on_goods_and_services (% of GDP),4.40,4.41,4.35,4.32,4.29,4.41,4.38,4.32
23,Imports_of_goods_and_services (% of GDP),16.42,16.45,15.35,14.65,15.01,15.25,14.58,13.28
24,Exports_of_goods_and_services (% of GDP),13.58,13.55,12.46,11.94,12.24,12.34,11.79,10.16
36,Inflation_rate:_all_items (Annual growth %),1.46,1.62,0.12,1.26,2.13,2.44,1.81,1.23
41,Long-term_interest_rates (%),2.35,2.54,2.14,1.84,2.33,2.91,2.14,0.89
42,Purchasing_power_parities (USD per USD),1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
58,Tertiary_attainment_in_population_aged_25-64 (%),43.91,44.22,44.63,45.67,46.36,47.43,48.34,50.06
71,Unemployment_rate:_total_labour_force (%),7.38,6.17,5.29,4.87,4.35,3.90,3.67,8.09
75,"Labour_compensation_per_unit_labour_input,_tot...",1.49,2.53,2.88,1.20,3.17,3.23,3.21,6.80
80,Population_growth_rates (%),0.70,0.74,0.74,0.73,0.63,0.53,0.46,0.35
90,Life_expectancy_at_birth (Years),78.80,78.90,78.70,78.70,78.60,78.70,78.90,77.30

In [10]:
indx_econ_df = new_econ_df.set_index("Stats")
indx_econ_df

,2013,2014,2015,2016,2017,2018,2019,2020
Stats,,,,,,,,
Real_GDP_growth (Annual growth %),1.84,2.29,2.71,1.67,2.26,2.92,2.29,-3.40
Net_saving_rate_in_household_disposable_income...,6.32,7.28,7.78,7.22,7.52,7.88,7.90,17.05
Tax_on_corporate_profits (% of GDP),2.09,2.26,2.12,1.95,1.54,1.32,1.34,1.32
Taxes_on_goods_and_services (% of GDP),4.40,4.41,4.35,4.32,4.29,4.41,4.38,4.32
Imports_of_goods_and_services (% of GDP),16.42,16.45,15.35,14.65,15.01,15.25,14.58,13.28
Exports_of_goods_and_services (% of GDP),13.58,13.55,12.46,11.94,12.24,12.34,11.79,10.16
Inflation_rate:_all_items (Annual growth %),1.46,1.62,0.12,1.26,2.13,2.44,1.81,1.23
Long-term_interest_rates (%),2.35,2.54,2.14,1.84,2.33,2.91,2.14,0.89
Purchasing_power_parities (USD per USD),1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Tertiary_attainment_in_population_aged_25-64 (%),43.91,44.22,44.63,45.67,46.36,47.43,48.34,50.06
Unemployment_rate:_total_labour_force (%),7.38,6.17,5.29,4.87,4.35,3.90,3.67,8.09
"Labour_compensation_per_unit_labour_input,_tot...",1.49,2.53,2.88,1.20,3.17,3.23,3.21,6.80
Population_growth_rates (%),0.70,0.74,0.74,0.73,0.63,0.53,0.46,0.35
Life_expectancy_at_birth (Years),78.80,78.90,78.70,78.70,78.60,78.70,78.90,77.30

In [11]:
tp_econ_df = indx_econ_df.T
tp_econ_df

Stats,Real_GDP_growth (Annual growth %),Net_saving_rate_in_household_disposable_income...,Tax_on_corporate_profits (% of GDP),Taxes_on_goods_and_services (% of GDP),Imports_of_goods_and_services (% of GDP),Exports_of_goods_and_services (% of GDP),Inflation_rate:_all_items (Annual growth %),Long-term_interest_rates (%),Purchasing_power_parities (USD per USD),Tertiary_attainment_in_population_aged_25-64 (%),Unemployment_rate:_total_labour_force (%),"Labour_compensation_per_unit_labour_input,_tot...",Population_growth_rates (%),Life_expectancy_at_birth (Years)
2013,1.84,6.32,2.09,4.40,16.42,13.58,1.46,2.35,1.0,43.91,7.38,1.49,0.70,78.8
2014,2.29,7.28,2.26,4.41,16.45,13.55,1.62,2.54,1.0,44.22,6.17,2.53,0.74,78.9
2015,2.71,7.78,2.12,4.35,15.35,12.46,0.12,2.14,1.0,44.63,5.29,2.88,0.74,78.7
2016,1.67,7.22,1.95,4.32,14.65,11.94,1.26,1.84,1.0,45.67,4.87,1.20,0.73,78.7
2017,2.26,7.52,1.54,4.29,15.01,12.24,2.13,2.33,1.0,46.36,4.35,3.17,0.63,78.6
2018,2.92,7.88,1.32,4.41,15.25,12.34,2.44,2.91,1.0,47.43,3.90,3.23,0.53,78.7
2019,2.29,7.90,1.34,4.38,14.58,11.79,1.81,2.14,1.0,48.34,3.67,3.21,0.46,78.9
2020,-3.40,17.05,1.32,4.32,13.28,10.16,1.23,0.89,1.0,50.06,8.09,6.80,0.35,77.3

In [12]:
tp_econ_df.dtypes

Stats
Real_GDP_growth (Annual growth %)                    float64
Net_saving_rate_in_household_disposable_income...    float64
Tax_on_corporate_profits (% of GDP)                  float64
Taxes_on_goods_and_services (% of GDP)               float64
Imports_of_goods_and_services (% of GDP)             float64
Exports_of_goods_and_services (% of GDP)             float64
Inflation_rate:_all_items (Annual growth %)          float64
Long-term_interest_rates (%)                         float64
Purchasing_power_parities (USD per USD)              float64
Tertiary_attainment_in_population_aged_25-64 (%)     float64
Unemployment_rate:_total_labour_force (%)            float64
Labour_compensation_per_unit_labour_input,_tot...    float64
Population_growth_rates (%)                          float64
Life_expectancy_at_birth (Years)                     float64
dtype: object

In [13]:
tp_econ_df.reset_index(inplace=True)
tp_econ_df

Stats,index,Real_GDP_growth (Annual growth %),Net_saving_rate_in_household_disposable_income...,Tax_on_corporate_profits (% of GDP),Taxes_on_goods_and_services (% of GDP),Imports_of_goods_and_services (% of GDP),Exports_of_goods_and_services (% of GDP),Inflation_rate:_all_items (Annual growth %),Long-term_interest_rates (%),Purchasing_power_parities (USD per USD),Tertiary_attainment_in_population_aged_25-64 (%),Unemployment_rate:_total_labour_force (%),"Labour_compensation_per_unit_labour_input,_tot...",Population_growth_rates (%),Life_expectancy_at_birth (Years)
0,2013,1.84,6.32,2.09,4.40,16.42,13.58,1.46,2.35,1.0,43.91,7.38,1.49,0.70,78.8
1,2014,2.29,7.28,2.26,4.41,16.45,13.55,1.62,2.54,1.0,44.22,6.17,2.53,0.74,78.9
2,2015,2.71,7.78,2.12,4.35,15.35,12.46,0.12,2.14,1.0,44.63,5.29,2.88,0.74,78.7
3,2016,1.67,7.22,1.95,4.32,14.65,11.94,1.26,1.84,1.0,45.67,4.87,1.20,0.73,78.7
4,2017,2.26,7.52,1.54,4.29,15.01,12.24,2.13,2.33,1.0,46.36,4.35,3.17,0.63,78.6
5,2018,2.92,7.88,1.32,4.41,15.25,12.34,2.44,2.91,1.0,47.43,3.90,3.23,0.53,78.7
6,2019,2.29,7.90,1.34,4.38,14.58,11.79,1.81,2.14,1.0,48.34,3.67,3.21,0.46,78.9
7,2020,-3.40,17.05,1.32,4.32,13.28,10.16,1.23,0.89,1.0,50.06,8.09,6.80,0.35,77.3

In [14]:
mapping = {tp_econ_df.columns[0]: 'Year'}
tp_econ_df = tp_econ_df.rename(columns=mapping)
tp_econ_df

Stats,Year,Real_GDP_growth (Annual growth %),Net_saving_rate_in_household_disposable_income (%),Tax_on_corporate_profits (% of GDP),Taxes_on_goods_and_services (% of GDP),Imports_of_goods_and_services (% of GDP),Exports_of_goods_and_services (% of GDP),Inflation_rate:_all_items (Annual growth %),Long-term_interest_rates (%),Purchasing_power_parities (USD per USD),Tertiary_attainment_in_population_aged_25-64 (%),Unemployment_rate:_total_labour_force (%),"Labour_compensation_per_unit_labour_input,_total_economy (Annual growth %)",Population_growth_rates (%),Life_expectancy_at_birth (Years)
0,2013,1.84,6.32,2.09,4.40,16.42,13.58,1.46,2.35,1.0,43.91,7.38,1.49,0.70,78.8
1,2014,2.29,7.28,2.26,4.41,16.45,13.55,1.62,2.54,1.0,44.22,6.17,2.53,0.74,78.9
2,2015,2.71,7.78,2.12,4.35,15.35,12.46,0.12,2.14,1.0,44.63,5.29,2.88,0.74,78.7
3,2016,1.67,7.22,1.95,4.32,14.65,11.94,1.26,1.84,1.0,45.67,4.87,1.20,0.73,78.7
4,2017,2.26,7.52,1.54,4.29,15.01,12.24,2.13,2.33,1.0,46.36,4.35,3.17,0.63,78.6
5,2018,2.92,7.88,1.32,4.41,15.25,12.34,2.44,2.91,1.0,47.43,3.90,3.23,0.53,78.7
6,2019,2.29,7.90,1.34,4.38,14.58,11.79,1.81,2.14,1.0,48.34,3.67,3.21,0.46,78.9
7,2020,-3.40,17.05,1.32,4.32,13.28,10.16,1.23,0.89,1.0,50.06,8.09,6.80,0.35,77.3

In [15]:
tp_econ_df = tp_econ_df.rename_axis(None, axis = 1)

In [16]:
tp_econ_df

,Year,Real_GDP_growth (Annual growth %),Net_saving_rate_in_household_disposable_income (%),Tax_on_corporate_profits (% of GDP),Taxes_on_goods_and_services (% of GDP),Imports_of_goods_and_services (% of GDP),Exports_of_goods_and_services (% of GDP),Inflation_rate:_all_items (Annual growth %),Long-term_interest_rates (%),Purchasing_power_parities (USD per USD),Tertiary_attainment_in_population_aged_25-64 (%),Unemployment_rate:_total_labour_force (%),"Labour_compensation_per_unit_labour_input,_total_economy (Annual growth %)",Population_growth_rates (%),Life_expectancy_at_birth (Years)
0,2013,1.84,6.32,2.09,4.40,16.42,13.58,1.46,2.35,1.0,43.91,7.38,1.49,0.70,78.8
1,2014,2.29,7.28,2.26,4.41,16.45,13.55,1.62,2.54,1.0,44.22,6.17,2.53,0.74,78.9
2,2015,2.71,7.78,2.12,4.35,15.35,12.46,0.12,2.14,1.0,44.63,5.29,2.88,0.74,78.7
3,2016,1.67,7.22,1.95,4.32,14.65,11.94,1.26,1.84,1.0,45.67,4.87,1.20,0.73,78.7
4,2017,2.26,7.52,1.54,4.29,15.01,12.24,2.13,2.33,1.0,46.36,4.35,3.17,0.63,78.6
5,2018,2.92,7.88,1.32,4.41,15.25,12.34,2.44,2.91,1.0,47.43,3.90,3.23,0.53,78.7
6,2019,2.29,7.90,1.34,4.38,14.58,11.79,1.81,2.14,1.0,48.34,3.67,3.21,0.46,78.9
7,2020,-3.40,17.05,1.32,4.32,13.28,10.16,1.23,0.89,1.0,50.06,8.09,6.80,0.35,77.3

In [17]:
tp_econ_df.rename(columns = {"Real_GDP_growth (Annual growth %)": "Ann_real_GDP_gwth_pct", 
                "Net_saving_rate_in_household_disposable_income (%)": "Net_savings_rate_household_disp_inc_pct", 
                "Tax_on_corporate_profits (% of GDP)": "Tax_on_corp_profits_PctofGDP",
                "Taxes_on_goods_and_services (% of GDP)": "Tax_on_goods_and_services_PctofGDP", 
                "Imports_of_goods_and_services (% of GDP)": "Imports_of_goods_and_services_PctofGDP",
                "Exports_of_goods_and_services (% of GDP)": "Exports_of_goods_and_services_PctofGDP", 
                "Inflation_rate:_all_items (Annual growth %)": "Infl_rate_all_items_ann_grwth_pct",
                "Long-term_interest_rates (%)": "LT_int_rate_pct", 
                "Unemployment_rate:_total_labour_force (%)": "Unemp_rate_total_pct",
                "Tertiary_attainment_in_population_aged_25-64 (%)": "Teritary_attainment_aged_25_to_64_pct",
                "Life_expectancy_at_birth (Years)": "Life_expectancy_yrs",
                "Population_growth_rates (%)": "Pop_grwth_rate_pct", 
                "Purchasing_power_parities (USD per USD)": "PPI_USD_per_USD", 
                "Labour_compensation_per_unit_labour_input,_total_economy (Annual growth %)": "Labor_comp_per_unit_labor_input_ann_growth_pct"
}, inplace = True)

In [18]:
tp_econ_df

,Year,Ann_real_GDP_gwth_pct,Net_savings_rate_household_disp_inc_pct,Tax_on_corp_profits_PctofGDP,Tax_on_goods_and_services_PctofGDP,Imports_of_goods_and_services_PctofGDP,Exports_of_goods_and_services_PctofGDP,Infl_rate_all_items_ann_grwth_pct,LT_int_rate_pct,PPI_USD_per_USD,Teritary_attainment_aged_25_to_64_pct,Unemp_rate_total_pct,Labor_comp_per_unit_labor_input_ann_growth_pct,Pop_grwth_rate_pct,Life_expectancy_yrs
0,2013,1.84,6.32,2.09,4.40,16.42,13.58,1.46,2.35,1.0,43.91,7.38,1.49,0.70,78.8
1,2014,2.29,7.28,2.26,4.41,16.45,13.55,1.62,2.54,1.0,44.22,6.17,2.53,0.74,78.9
2,2015,2.71,7.78,2.12,4.35,15.35,12.46,0.12,2.14,1.0,44.63,5.29,2.88,0.74,78.7
3,2016,1.67,7.22,1.95,4.32,14.65,11.94,1.26,1.84,1.0,45.67,4.87,1.20,0.73,78.7
4,2017,2.26,7.52,1.54,4.29,15.01,12.24,2.13,2.33,1.0,46.36,4.35,3.17,0.63,78.6
5,2018,2.92,7.88,1.32,4.41,15.25,12.34,2.44,2.91,1.0,47.43,3.90,3.23,0.53,78.7
6,2019,2.29,7.90,1.34,4.38,14.58,11.79,1.81,2.14,1.0,48.34,3.67,3.21,0.46,78.9
7,2020,-3.40,17.05,1.32,4.32,13.28,10.16,1.23,0.89,1.0,50.06,8.09,6.80,0.35,77.3

In [19]:
tp_econ_df.dtypes

Year                                               object
Ann_real_GDP_gwth_pct                             float64
Net_savings_rate_household_disp_inc_pct           float64
Tax_on_corp_profits_PctofGDP                      float64
Tax_on_goods_and_services_PctofGDP                float64
Imports_of_goods_and_services_PctofGDP            float64
Exports_of_goods_and_services_PctofGDP            float64
Infl_rate_all_items_ann_grwth_pct                 float64
LT_int_rate_pct                                   float64
PPI_USD_per_USD                                   float64
Teritary_attainment_aged_25_to_64_pct             float64
Unemp_rate_total_pct                              float64
Labor_comp_per_unit_labor_input_ann_growth_pct    float64
Pop_grwth_rate_pct                                float64
Life_expectancy_yrs                               float64
dtype: object

In [28]:
tp_econ_df['Year'] = pd.to_datetime(tp_econ_df['Year'], format='%Y')
tp_econ_df['Year'] = tp_econ_df['Year'].dt.to_period('Y')

In [32]:
tp_econ_df

,Year,Ann_real_GDP_gwth_pct,Net_savings_rate_household_disp_inc_pct,Tax_on_corp_profits_PctofGDP,Tax_on_goods_and_services_PctofGDP,Imports_of_goods_and_services_PctofGDP,Exports_of_goods_and_services_PctofGDP,Infl_rate_all_items_ann_grwth_pct,LT_int_rate_pct,PPI_USD_per_USD,Teritary_attainment_aged_25_to_64_pct,Unemp_rate_total_pct,Labor_comp_per_unit_labor_input_ann_growth_pct,Pop_grwth_rate_pct,Life_expectancy_yrs
0,2013,1.84,6.32,2.09,4.40,16.42,13.58,1.46,2.35,1.0,43.91,7.38,1.49,0.70,78.8
1,2014,2.29,7.28,2.26,4.41,16.45,13.55,1.62,2.54,1.0,44.22,6.17,2.53,0.74,78.9
2,2015,2.71,7.78,2.12,4.35,15.35,12.46,0.12,2.14,1.0,44.63,5.29,2.88,0.74,78.7
3,2016,1.67,7.22,1.95,4.32,14.65,11.94,1.26,1.84,1.0,45.67,4.87,1.20,0.73,78.7
4,2017,2.26,7.52,1.54,4.29,15.01,12.24,2.13,2.33,1.0,46.36,4.35,3.17,0.63,78.6
5,2018,2.92,7.88,1.32,4.41,15.25,12.34,2.44,2.91,1.0,47.43,3.90,3.23,0.53,78.7
6,2019,2.29,7.90,1.34,4.38,14.58,11.79,1.81,2.14,1.0,48.34,3.67,3.21,0.46,78.9
7,2020,-3.40,17.05,1.32,4.32,13.28,10.16,1.23,0.89,1.0,50.06,8.09,6.80,0.35,77.3

In [33]:
tp_econ_df.dtypes

Year                                              period[A-DEC]
Ann_real_GDP_gwth_pct                                   float64
Net_savings_rate_household_disp_inc_pct                 float64
Tax_on_corp_profits_PctofGDP                            float64
Tax_on_goods_and_services_PctofGDP                      float64
Imports_of_goods_and_services_PctofGDP                  float64
Exports_of_goods_and_services_PctofGDP                  float64
Infl_rate_all_items_ann_grwth_pct                       float64
LT_int_rate_pct                                         float64
PPI_USD_per_USD                                         float64
Teritary_attainment_aged_25_to_64_pct                   float64
Unemp_rate_total_pct                                    float64
Labor_comp_per_unit_labor_input_ann_growth_pct          float64
Pop_grwth_rate_pct                                      float64
Life_expectancy_yrs                                     float64
dtype: object

In [34]:
tp_econ_df.to_csv("final_econ_data.csv", index=False)